import { CourseId, Word } from './types';

// Helper to create words compactly
const w = (id: string, en: string, zh: string, type: string = '', phonetic: string = '', example: string = ''): Word => ({
  id, en, zh, type, phonetic, example
});

export const WORD_DATA: Record<CourseId, Word[]> = {
  [CourseId.JUNIOR_1600]: [
    w('j1', 'ability', '能力；才能', 'n.', '/əˈbɪləti/', 'He has the ability to do the job.'),
    w('j2', 'abroad', '到国外；在国外', 'adv.', '/əˈbrɔːd/', 'He went abroad for further study.'),
    w('j3', 'absent', '缺席；不在', 'adj.', '/ˈæbsənt/', 'He was absent from school yesterday.'),
    w('j4', 'accent', '口音；重音', 'n.', '/ˈæksent/', 'He speaks with a strong accent.'),
    w('j5', 'accept', '接受', 'v.', '/əkˈsept/', 'I accepted his invitation.'),
    w('j6', 'accident', '事故，意外的事', 'n.', '/ˈæksɪdənt/', 'He was injured in a car accident.'),
    w('j7', 'ache', '痛，疼痛', 'v.& n.', '/eɪk/', 'My head aches.'),
    w('j8', 'achieve', '达到，取得', 'v.', '/əˈtʃiːv/', 'He achieved his goal.'),
    w('j9', 'across', '横过，穿过', 'prep.', '/əˈkrɔːs/', 'He walked across the street.'),
    w('j10', 'act', '表演；行动', 'v.', '/ækt/', 'Think before you act.'),
    w('j11', 'action', '行动', 'n.', '/ˈækʃn/', 'Actions speak louder than words.'),
    w('j12', 'active', '积极的', 'adj.', '/ˈæktɪv/', 'He is an active member of the club.'),
    w('j13', 'activity', '活动', 'n.', '/ækˈtɪvəti/', 'Outdoor activities are healthy.'),
    w('j14', 'add', '增加，添加', 'v.', '/æd/', 'Add some sugar to the tea.'),
    w('j15', 'address', '地址', 'n.', '/əˈdres/', 'What is your home address?'),
    w('j16', 'advantage', '优点；好处', 'n.', '/ədˈvɑːntɪdʒ/', 'Technology has many advantages.'),
    w('j17', 'advertisement', '广告', 'n.', '/ədˈvɜːtɪsmənt/', 'I saw an advertisement for a new car.'),
    w('j18', 'advice', '忠告，劝告', 'n.', '/ədˈvaɪs/', 'Take my advice.'),
    w('j19', 'advise', '忠告，劝告', 'v.', '/ədˈvaɪz/', 'I advise you to go home.'),
    w('j20', 'afford', '负担得起', 'v.', '/əˈfɔːd/', 'I cannot afford this car.'),
    w('j21', 'afraid', '害怕的', 'adj.', '/əˈfreɪd/', 'Don’t be afraid.'),
    w('j22', 'after', '在……之后', 'prep.', '/ˈɑːftə(r)/', 'After dinner, we went for a walk.'),
    w('j23', 'afternoon', '下午', 'n.', '/ˌɑːftəˈnuːn/', 'Good afternoon.'),
    w('j24', 'again', '再一次', 'adv.', '/əˈɡen/', 'Try again.'),
    w('j25', 'against', '对着，反对', 'prep.', '/əˈɡenst/', 'Are you for or against the plan?'),
    w('j26', 'age', '年龄', 'n.', '/eɪdʒ/', 'He is the same age as me.'),
    w('j27', 'ago', '以前', 'adv.', '/əˈɡəʊ/', 'Long long ago.'),
    w('j28', 'agree', '同意', 'v.', '/əˈɡriː/', 'I agree with you.'),
    w('j29', 'agreement', '同意；协议', 'n.', '/əˈɡriːmənt/', 'They signed an agreement.'),
    w('j30', 'air', '空气', 'n.', '/eə(r)/', 'Fresh air.'),
    w('j31', 'airline', '航空公司', 'n.', '/ˈeəlaɪn/', 'Which airline are you flying with?'),
    w('j32', 'airplane', '飞机', 'n.', '/ˈeəpleɪn/', 'The airplane landed safely.'),
    w('j33', 'airport', '机场', 'n.', '/ˈeəpɔːt/', 'We arrived at the airport on time.'),
    w('j34', 'alive', '活着的', 'adj.', '/əˈlaɪv/', 'The fish is still alive.'),
    w('j35', 'all', '全部的', 'adj.', '/ɔːl/', 'All the students are here.'),
    w('j36', 'allow', '允许，准许', 'v.', '/əˈlaʊ/', 'Smoking is not allowed here.'),
    w('j37', 'almost', '几乎，差不多', 'adv.', '/ˈɔːlməʊst/', 'It is almost time to go.'),
    w('j38', 'alone', '单独的，孤独的', 'adj.', '/əˈləʊn/', 'She lives alone.'),
    w('j39', 'along', '沿着；顺着', 'prep.', '/əˈlɒŋ/', 'Walk along the river.'),
    w('j40', 'aloud', '大声地', 'adv.', '/əˈlaʊd/', 'Read the text aloud.'),
    w('j41', 'already', '已经', 'adv.', '/ɔːlˈredi/', 'I have already finished my homework.'),
    w('j42', 'also', '也', 'adv.', '/ˈɔːlsəʊ/', 'He speaks English and also French.'),
    w('j43', 'although', '虽然，尽管', 'conj.', '/ɔːlˈðəʊ/', 'Although it rained, we enjoyed the trip.'),
    w('j44', 'always', '总是', 'adv.', '/ˈɔːlweɪz/', 'He is always late.'),
    w('j45', 'amazing', '惊人的', 'adj.', '/əˈmeɪzɪŋ/', 'The view is amazing.'),
    w('j46', 'America', '美国', 'n.', '/əˈmerɪkə/', 'He is from America.'),
    w('j47', 'among', '在……中间', 'prep.', '/əˈmʌŋ/', 'He is popular among students.'),
    w('j48', 'ancient', '古代的，古老的', 'adj.', '/ˈeɪnʃənt/', 'China has an ancient history.'),
    w('j49', 'and', '和，又', 'conj.', '/ænd/', 'You and I.'),
    w('j50', 'angry', '生气的', 'adj.', '/ˈæŋɡri/', 'Don’t be angry with me.'),
  ],
  [CourseId.JUNIOR_PHRASES]: [
    w('jp1', 'a bit (of)', '有一点，一会儿', 'phrase'),
    w('jp2', 'after all', '毕竟，终究', 'phrase'),
    w('jp3', 'agree with', '同意...的意见', 'phrase'),
    w('jp4', 'all over', '到处，遍及', 'phrase'),
    w('jp5', 'as a result', '结果', 'phrase'),
    w('jp6', 'ask for', '请求，要求', 'phrase'),
    w('jp7', 'at first', '起初，开始时', 'phrase'),
    w('jp8', 'at least', '至少', 'phrase'),
    w('jp9', 'at once', '立刻，马上', 'phrase'),
    w('jp10', 'be able to', '能够', 'phrase'),
    w('jp11', 'be afraid of', '害怕', 'phrase'),
    w('jp12', 'be angry with', '对……生气', 'phrase'),
    w('jp13', 'be away from', '离开', 'phrase'),
    w('jp14', 'be busy doing', '忙于做……', 'phrase'),
    w('jp15', 'be careful', '小心', 'phrase'),
    w('jp16', 'be excited about', '对……感到兴奋', 'phrase'),
    w('jp17', 'be famous for', '因……而著名', 'phrase'),
    w('jp18', 'be full of', '充满', 'phrase'),
    w('jp19', 'be good at', '擅长', 'phrase'),
    w('jp20', 'be interested in', '对……感兴趣', 'phrase'),
    w('jp21', 'be late for', '迟到', 'phrase'),
    w('jp22', 'be made of', '由……制成（物理）', 'phrase'),
    w('jp23', 'be made from', '由……制成（化学）', 'phrase'),
    w('jp24', 'be pleased with', '对……感到满意', 'phrase'),
    w('jp25', 'be proud of', '以……为骄傲', 'phrase'),
    w('jp26', 'be used to', '习惯于', 'phrase'),
    w('jp27', 'belong to', '属于', 'phrase'),
    w('jp28', 'break down', '出故障', 'phrase'),
    w('jp29', 'break out', '爆发', 'phrase'),
    w('jp30', 'bring up', '抚养', 'phrase'),
  ],
  [CourseId.SENIOR_3500]: [
    w('s1', 'abandon', '抛弃，舍弃，放弃', 'v.', '/əˈbændən/', 'They had to abandon the car.'),
    w('s2', 'abnormal', '反常的，变态的', 'adj.', '/æbˈnɔːml/', 'It is abnormal weather.'),
    w('s3', 'abolish', '废除，废止', 'v.', '/əˈbɒlɪʃ/', 'Slavery was abolished.'),
    w('s4', 'abortion', '流产，堕胎', 'n.', '/əˈbɔːʃn/'),
    w('s5', 'abrupt', '突然的，意外的', 'adj.', '/əˈbrʌpt/', 'An abrupt stop.'),
    w('s6', 'absence', '不在，缺席', 'n.', '/ˈæbsəns/'),
    w('s7', 'absolute', '完全，全部，绝对的', 'adj.', '/ˈæbsəluːt/'),
    w('s8', 'absorb', '吸收，使全神贯注', 'v.', '/əbˈzɔːb/'),
    w('s9', 'abstract', '抽象的', 'adj.', '/ˈæbstrækt/'),
    w('s10', 'absurd', '荒谬的', 'adj.', '/əbˈsɜːd/'),
    w('s11', 'abuse', '滥用，虐待', 'v.', '/əˈbjuːs/', 'Drug abuse is a serious problem.'),
    w('s12', 'academic', '学院的，学术的', 'adj.', '/ˌækəˈdemɪk/', 'Academic performance.'),
    w('s13', 'accelerate', '加速，促进', 'v.', '/əkˈseləreɪt/', 'The car accelerated.'),
    w('s14', 'access', '通道，入径', 'n.', '/ˈækses/', 'Internet access.'),
    w('s15', 'accommodation', '住宿，膳宿', 'n.', '/əˌkɒməˈdeɪʃn/', 'Hotel accommodation.'),
    w('s16', 'accompany', '陪同，陪伴', 'v.', '/əˈkʌmpəni/', 'She accompanied him.'),
    w('s17', 'accomplish', '完成', 'v.', '/əˈkʌmplɪʃ/', 'Mission accomplished.'),
    w('s18', 'account', '账目；描述', 'n.', '/əˈkaʊnt/'),
    w('s19', 'accumulate', '积累，积聚', 'v.', '/əˈkjuːmjəleɪt/', 'Accumulate wealth.'),
    w('s20', 'accurate', '准确的，精确的', 'adj.', '/ˈækjərət/', 'An accurate description.'),
    w('s21', 'accuse', '指责；控告', 'v.', '/əˈkjuːz/', 'He was accused of theft.'),
    w('s22', 'accustomed', '习惯于', 'adj.', '/əˈkʌstəmd/', 'I am accustomed to the heat.'),
    w('s23', 'acknowledge', '承认；致谢', 'v.', '/əkˈnɒlɪdʒ/', 'He acknowledged his mistake.'),
    w('s24', 'acquire', '获得，取得', 'v.', '/əˈkwaɪə(r)/', 'Acquire knowledge.'),
    w('s25', 'adapt', '适应；改编', 'v.', '/əˈdæpt/', 'Adapt to new environment.'),
    w('s26', 'addiction', '沉溺，成瘾', 'n.', '/əˈdɪkʃn/', 'Addiction to games.'),
    w('s27', 'address', '地址；演讲', 'n.', '/əˈdres/'),
    w('s28', 'adequate', '合适的，合乎需要的', 'adj.', '/ˈædɪkwət/', 'Adequate food.'),
    w('s29', 'adjust', '调整，调节', 'v.', '/əˈdʒʌst/', 'Adjust the volume.'),
    w('s30', 'administration', '管理，行政', 'n.', '/ədˌmɪnɪˈstreɪʃn/'),
    w('s31', 'admire', '钦佩；羡慕', 'v.', '/ədˈmaɪə(r)/', 'I admire his courage.'),
    w('s32', 'admit', '承认；准许进入', 'v.', '/ədˈmɪt/', 'He admitted stealing the money.'),
    w('s33', 'adolescence', '青春期', 'n.', '/ˌædəˈlesns/'),
    w('s34', 'adopt', '收养；采用', 'v.', '/əˈdɒpt/', 'They adopted a child.'),
    w('s35', 'adore', '崇拜；爱慕', 'v.', '/əˈdɔː(r)/'),
    w('s36', 'adult', '成年人', 'n.', '/ˈædʌlt/'),
    w('s37', 'advance', '前进；提升', 'v.', '/ədˈvɑːns/'),
    w('s38', 'advantage', '优点；好处', 'n.', '/ədˈvɑːntɪdʒ/'),
    w('s39', 'adventure', '冒险；奇遇', 'n.', '/ədˈventʃə(r)/'),
    w('s40', 'advertise', '登广告', 'v.', '/ˈædvətaɪz/'),
    w('s41', 'advocate', '拥护；提倡', 'v.', '/ˈædvəkeɪt/'),
    w('s42', 'affair', '事；事情', 'n.', '/əˈfeə(r)/'),
    w('s43', 'affect', '影响', 'v.', '/əˈfekt/'),
    w('s44', 'affection', '喜爱；钟爱', 'n.', '/əˈfekʃn/'),
    w('s45', 'afford', '负担得起', 'v.', '/əˈfɔːd/'),
    w('s46', 'agency', '代理机构', 'n.', '/ˈeɪdʒənsi/'),
    w('s47', 'agenda', '议程', 'n.', '/əˈdʒendə/'),
    w('s48', 'agent', '代理人', 'n.', '/ˈeɪdʒənt/'),
    w('s49', 'aggression', '侵略', 'n.', '/əˈɡreʃn/'),
    w('s50', 'aggressive', '侵略的；好斗的', 'adj.', '/əˈɡresɪv/'),
  ],
  [CourseId.SENIOR_PHRASES]: [
    w('sp1', 'account for', '说明……的原因', 'phrase'),
    w('sp2', 'accuse...of...', '指责，控告', 'phrase'),
    w('sp3', 'adapt to', '适应', 'phrase'),
    w('sp4', 'add up to', '合计达', 'phrase'),
    w('sp5', 'adhere to', '坚持，粘附', 'phrase'),
    w('sp6', 'agree on', '就……达成一致', 'phrase'),
    w('sp7', 'aim at', '瞄准，针对', 'phrase'),
    w('sp8', 'allow for', '考虑到', 'phrase'),
    w('sp9', 'answer for', '对……负责', 'phrase'),
    w('sp10', 'appeal to', '呼吁；吸引', 'phrase'),
    w('sp11', 'apply for', '申请', 'phrase'),
    w('sp12', 'approve of', '赞成', 'phrase'),
    w('sp13', 'arise from', '由……引起', 'phrase'),
    w('sp14', 'arrange for', '安排', 'phrase'),
    w('sp15', 'arrive at', '达成（协议等）', 'phrase'),
    w('sp16', 'ask after', '问候', 'phrase'),
    w('sp17', 'assign to', '指派给', 'phrase'),
    w('sp18', 'associate with', '与……交往', 'phrase'),
    w('sp19', 'attach to', '附属于', 'phrase'),
    w('sp20', 'attempt at', '尝试', 'phrase'),
    w('sp21', 'attend to', '处理，照料', 'phrase'),
    w('sp22', 'attribute to', '归因于', 'phrase'),
    w('sp23', 'back up', '支持，倒退', 'phrase'),
    w('sp24', 'bear in mind', '记住', 'phrase'),
    w('sp25', 'believe in', '信任', 'phrase'),
    w('sp26', 'belong to', '属于', 'phrase'),
    w('sp27', 'blow up', '爆炸，充气', 'phrase'),
    w('sp28', 'break away from', '脱离', 'phrase'),
    w('sp29', 'break down', '分解；崩溃', 'phrase'),
    w('sp30', 'break in', '闯入；插话', 'phrase'),
  ]
};

export const COURSE_INFO = {
  [CourseId.JUNIOR_1600]: { title: '初中英语1600词', desc: '中考核心基础词汇', color: 'bg-green-100 text-green-800 border-green-200' },
  [CourseId.JUNIOR_PHRASES]: { title: '初中重点短语', desc: '中考高频短语搭配', color: 'bg-emerald-100 text-emerald-800 border-emerald-200' },
  [CourseId.SENIOR_3500]: { title: '高中英语3500词', desc: '高考必背核心词汇', color: 'bg-blue-100 text-blue-800 border-blue-200' },
  [CourseId.SENIOR_PHRASES]: { title: '高中超纲/重点短语', desc: '提分必备难点短语', color: 'bg-indigo-100 text-indigo-800 border-indigo-200' },
};